import dayjs from "@calcom/dayjs";
import type { PrismaClient } from "@calcom/prisma";
import { RecallHistoryStatus } from "@calcom/prisma/enums";

import { createDentalLogger } from "../resilience/dental-logger";
import { RECALL_METADATA_KEY } from "./constants";

export type RecallMonthlyStats = {
  /** Recalls sent (email + SMS) in the given month. */
  sentThisMonth: number;
  /** Bookings created via recall links in the given month — the core KPI. */
  convertedThisMonth: number;
};

/**
 * Appends the recall reference to the practice booking link so the booker
 * carries it into booking metadata (`metadata[recallRef]=<token>`).
 */
export function appendRecallRefToBookingLink(bookingLink: string, optOutToken: string): string {
  const separator = bookingLink.includes("?") ? "&" : "?";
  return `${bookingLink}${separator}metadata[${RECALL_METADATA_KEY}]=${encodeURIComponent(optOutToken)}`;
}

/** Reads the recall reference out of untrusted booking metadata. */
export function extractRecallRefFromMetadata(metadata: unknown): string | null {
  if (typeof metadata !== "object" || metadata === null) {
    return null;
  }

  const value = (metadata as Record<string, unknown>)[RECALL_METADATA_KEY];
  return typeof value === "string" && value.length > 0 ? value : null;
}

/**
 * Attributes bookings to the recall outreach that generated them and
 * aggregates the resulting dashboard KPI ("appointments generated by recall").
 */
export class RecallConversionService {
  private readonly log = createDentalLogger({ module: "recall-conversion" });

  constructor(private readonly prisma: PrismaClient) {}

  /**
   * Marks the recall cycle behind `recallRef` as converted. Idempotent: the
   * first booking wins, later bookings via the same link are ignored.
   */
  async attributeBooking(recallRef: string, bookingUid: string): Promise<boolean> {
    const result = await this.prisma.recallHistory.updateMany({
      where: {
        optOutToken: recallRef,
        status: RecallHistoryStatus.SENT,
        convertedAt: null,
      },
      data: {
        convertedBookingUid: bookingUid,
        convertedAt: new Date(),
      },
    });

    const attributed = result.count > 0;
    if (attributed) {
      this.log.info("Booking attributed to recall", { bookingUid });
    }
    return attributed;
  }

  async getMonthlyStats(teamId: number, referenceDate: Date = new Date()): Promise<RecallMonthlyStats> {
    const monthStart = dayjs(referenceDate).startOf("month").toDate();
    const monthEnd = dayjs(referenceDate).endOf("month").toDate();

    const [sentThisMonth, convertedThisMonth] = await Promise.all([
      this.prisma.recallHistory.count({
        where: {
          teamId,
          status: RecallHistoryStatus.SENT,
          sentAt: { gte: monthStart, lte: monthEnd },
        },
      }),
      this.prisma.recallHistory.count({
        where: {
          teamId,
          convertedAt: { gte: monthStart, lte: monthEnd },
        },
      }),
    ]);

    return { sentThisMonth, convertedThisMonth };
  }
}
