/** Parses env vars that Cal.com treats as boolean (`"true"` or `"1"`). */
export function parseBooleanEnv(value: string | undefined): boolean {
  return value === "true" || value === "1";
}

export const DENTAL_ENV = {
  ENCRYPTION_ENABLED: "DENTAL_ENCRYPTION_ENABLED",
  DISABLE_TRACKING: "DENTAL_DISABLE_TRACKING",
  DISABLE_DENORMALIZED: "DENTAL_DISABLE_DENORMALIZED",
  DISABLE_THIRD_PARTY_ANALYTICS: "DENTAL_DISABLE_THIRD_PARTY_ANALYTICS",
  NEXT_PUBLIC_COMPLIANCE_MODE: "NEXT_PUBLIC_DENTAL_COMPLIANCE_MODE",
  NEXT_PUBLIC_ENCRYPTION_ENABLED: "NEXT_PUBLIC_DENTAL_ENCRYPTION_ENABLED",
  NEXT_PUBLIC_DISABLE_TRACKING: "NEXT_PUBLIC_DENTAL_DISABLE_TRACKING",
  NEXT_PUBLIC_DISABLE_THIRD_PARTY_ANALYTICS: "NEXT_PUBLIC_DENTAL_DISABLE_THIRD_PARTY_ANALYTICS",
} as const;
